name: qBittorrent
enable: true
priority: 6
height: 6
padding: 3
extend:
  ColNum:
    val: "2"
    desc: 展示多少列
    priority: 200
  NameLen:
    val: "20"
    desc: 名字长度限制
    priority: 210
  Username:
    val: admin
    desc: 用户名
    priority: 200
  Password:
    val: adminadmin
    desc: 密码
    priority: 190
  HostPort:
    val: http://192.168.100.4:18080
    desc: ip和端口
    priority: 180
  SearchNum:
    val: "20"
    desc: 搜索展示数量
    priority: 170
