name: transmission
enable: true
priority: 60
padding: 3
height: 4
extend:
  DownloadPath:
    val: /downloads
    desc: 下载路径
    priority: 100
  HostPort:
    val: 127.0.0.1:9091
    desc: ip和端口
    priority: 180
  UserName:
    val: 用户名
    desc: 用户名
    priority: 170
  Password:
    val: password
    desc: 密码
    priority: 160